### PR TITLE
Added user inside context

### PR DESCRIPTION
**Pull request by vitorgamer58**
Fixes https://github.com/herbsjs/buchu/issues/84

## Proposed Changes

1. Added injection in the defaultController function so that req.user data can be accessed within usecase steps through ctx.di

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by dalssoft** [comment]
@vitorgamer58 great contrib!

did you used `git cz` to create the commit? is it marked as `breaking change`?

**Comment by dalssoft** [comment]
@vitorgamer58 also, we need a PR to update the docs with info about a new variable `user` on the `ctx`.

https://herbsjs.org/docs/usecase/steps#step-context-ctx

**Comment by vitorgamer58** [comment]
> @vitorgamer58 great contrib!
> 
> did you used `git cz` to create the commit? is it marked as `breaking change`?

No, I didn't use `git cz`, and it's not marked as `breaking change`.

**Comment by vitorgamer58** [comment]
@dalssoft I did the commit using `cz` and market it as a `breaking change`

**Pull request merged**
