### PR TITLE
Bring linter to root path and update the ci pipeline

### PR DESCRIPTION
**Pull request by italojs**
## Problem

Using the linter only in pipeline ci is unproductive, you need to wait for the pipeline to run to check if everything is ok

## Proposed Changes

- Bring the linter for root path and added scripts in package.json to run the linter locally.
- Remove the super linter and execute the ESlinter from the root path's project

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by jhomarolo** [comment]
What is the gain that this PR brings?

**Comment by italojs** [comment]
As I said in the problem session, using the linter only in pipeline ci is unproductive, because you need to wait for the pipeline to run to check if everything is ok, so bring the linter to the project I can run the linter before commit or push the code, so I dont need to wait for the PR pipeline to check if my linter is correct or not.

**Comment by jhomarolo-vortx** [comment]
In order to maintain a standard among the projects, could you please remove the other actions then?

Once you're done, let me know to approve all PR's at once

**Comment by italojs** [comment]
https://github.com/herbsjs/suma2text/pull/10
https://github.com/herbsjs/suma/pull/20
https://github.com/herbsjs/herbs-snippets/pull/6
https://github.com/herbsjs/herbs2gql/pull/15
https://github.com/herbsjs/herbsshelf/pull/3
https://github.com/herbsjs/gotu/pull/27

Let me know if I forgot some repository :)

**Comment by jhomarolo** [comment]
I think these two were missing
https://github.com/herbsjs/todolist-on-herbs
https://github.com/herbsjs/herbs2repl (this one needs the whole github folder)

I'll approve this PR but I'll wait for those

Thank you for your great maintenance contribution

**Pull request merged**
